name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm ci
    - name: Build pdf
      run: npm start
    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: Update Resume PDF

        # Optional name of the branch the commit should be pushed to
        # Required if Action is used in Workflow listening to the `pull_request` event
        branch: ${{ github.head_ref }}

        # Optional glob pattern of files which should be added to the commit
        file_pattern: ./devin-clark-resume.pdf
